### ISSUE TITLE
Documentation Link Doesnt work

### ISSUE THREAD

**Issue by ajgrinds** [DiscordBotList/DBL-Python-Library#11]
## Expected Behavior
It should show documentation

## Current Behavior
It doesn't show documentation

## Development Environemt
IPv4

## Steps to Reproduce
1. click [here](http://dblpy.readthedocs.io/en/v0.1.3/)
### OR
2. click [here](https://discordbots.org/api/docs#pylib)

## Context
Im trying to use the API and Im getting errors
Documentation is probably the most useful

**Comment by shivaco** [comment]
https://dblpy.readthedocs.io/en/latest/index.html
DBL docs lead to an outdated (0.1.3) version of docs. Keeping this open until everything is sorted out.
