### ISSUE TITLE
Outdated background task example

### ISSUE THREAD

**Issue by lganWebb** [DiscordBotList/DBL-Python-Library#15]
Issue tracker is **ONLY** used for reporting bugs with __dblpy__. NO NEW FEATURES ACCEPTED! Use [stackoverflow](https://stackoverflow.com) for supporting general issues.

The example in the [API Examples](https://discordbots.org/api/docs#pylib) is slightly out-dated.

## Expected Behavior
The new `discord.ext.tasks` module has been added to the library.

## Current Behavior
This method still works, however is not the most efficient way to do it.

## Development Environemt
Python 3.7.0

## Steps to Reproduce
No steps

## Context
Doesn't affect me, however would be better to have an updated version.

## Possible Solution
I have put together an updated code block.
```py
import dbl
import discord
from discord.ext import commands, tasks

import asyncio
import logging


class DiscordBotsOrgAPI(commands.Cog):
    """Handles interactions with the discordbots.org API"""

    def __init__(self, bot):
        self.bot = bot
        self.token = 'dbl_token' # set this to your DBL token
        self.dblpy = dbl.Client(self.bot, self.token)
        self.update_stats.start()

    @tasks.loop(minutes=30.0)
    async def update_stats(self):
    """This function runs every 30 minutes to automatically update your server count"""
    logger.info('Attempting to post server count')
    try:
        await self.dblpy.post_guild_count()
        logger.info('Posted server count ({})'.format(self.dblpy.guild_count()))
    except Exception as e:
        logger.exception('Failed to post server count\n{}: {}'.format(type(e).__name__, e))
    
    @update_stats.before_loop
    async def before_loop(self):
    """This will make sure the bot is ready before starting the task"""
        await self.bot.wait_until_ready()

def setup(bot):
    global logger
    logger = logging.getLogger('bot')
    bot.add_cog(DiscordBotsOrgAPI(bot))
```

## Detailed Description
Make it more efficient and up-to-date.

## Possible Implementation
N/A

**Comment by shivaco** [comment]
Just a little heads up, all dblpy Client functions wait until the bot is ready before executing.
