### ISSUE TITLE
'DBLClient' has no attribute '_webserver'

### ISSUE THREAD

**Issue by Soheab** [DiscordBotList/DBL-Python-Library#16]
## Expected Behavior
It should close all connections.

## Current Behavior
Raises a AttributeError error.

## Development Environemt
Python: 3.7.4
discord.py: 1.3.0
dblpy: Latest (0.3.2)
OS: windows 10 pro edu insider preview

## Steps to Reproduce
dbf = dbl.DBLClient(self.bot, self.config.discordbotsorg.token)
1. try closing connection by doing "await dbf.close()"
2. it should give the error

my code: https://paste.alexflipnote.dev/eguqacetah.py

## Context
i want to close all connection but thats not possible if this error happens.

## Possible Solution
not sure but removing "await self._webserver.stop()" from close maybe?

**Comment by shivaco** [comment]
The error appears due to the built-in webhook not being used whereas `DBLClient.close` attempts to access it.
