### ISSUE TITLE
Having problems when using example: dbl has no attribute Client

### ISSUE THREAD

**Issue by TIBI4** [DiscordBotList/DBL-Python-Library#18]
## Expected Behavior
Example from https://discordbots.org/api/docs#pylib should work.

## Current Behavior
It does not work, and says `AttributeError: module 'dbl' has no attribute 'Client'`.

## Development Environemt

Python 3, DBLpy v0.3.2, Linux Debian 9.

## Steps to Reproduce

Just use the same code you use but with the latest update.

## Context
I was upgrading Discord.py to latest version, as it had many breaking changes.

## Possible Solution

Just update https://discordbots.org/api/docs#pylib to be in the same version as v0.3.2 and has breaking changes announced here https://dblpy.readthedocs.io/en/latest/whats_new.html `BREAKING CHANGE: Client class has been renamed to DBLClient
`.

**Comment by shivaco** [comment]
@tonkku107
