### ISSUE TITLE
Issues with the Wrapper and Example 

### ISSUE THREAD

**Issue by fourjr** [DiscordBotList/DBL-Python-Library#2]
**Example**
- Messy imports
- Unused import `asyncio `
- Double dblpy imports when you can just have the from import
- Unused Client after creating it, don't think it works
- Client should created in init with bot.loop as a provided parameter
- Bot ID and Guild Count should be retrieved from the bot object available in the Cog Init
- Cog doesn't have the setup function which is necessary for discord.py (please test the example)
- Unused session is created in init
- In init, `bot = bot` should be `self.bot = bot `
- In the last line, with a json.dumps, there should either be a indent of 2 or 4 provided as a kwarg. 
- ~~An example of background task (with an interval of maybe 3 hours) of posting server count~~ Refer to below @MattIPv4 replies
- Class functions should take self as a parameter 
- Use the Python logging module instead of print() 
- Demonstrate other `Client ` methods as well

**Wrapper**
- DBL Token and Bot object should be recieved as args into `Client `
- Session, loop and timeout should be kwargs into `Client `
- With the above changes, there should be no parameter needed to be passed into `get_server_count` and `post_server_count` as it can be retrieved from the bot object passed from init 
- Ratelimits handling 
- Docstrings, above is yours, and below mine modified for `Client `
```
The `event loop`_ to use for asynchronous operations. Defaults to ``None``,
in which case the default event loop is used via ``asyncio.get_event_loop()``.
```
```
The `event loop`_ to use for asynchronous operations. 
Defaults to ``asyncio.get_event_loop()``.
```

**Comment by MattIPv4** [comment]
Additionally to comply to PEP8 which an example really should, you should have two linebreaks before your class declaration.
And following d.py best practices your file at the top and class should have descriptions.

**Comment by MattIPv4** [comment]
In the example I would also demonstrate hooking into the guild join/leave events and the on ready event for posting stats.

**Comment by fourjr** [comment]
It shouldn't hook into join/leave imo, because of API ratelimits.

**Comment by MattIPv4** [comment]
As this is a full library for API contact, I would personally expect the library to handle ratelimiting itself so that you can do what you want and it will stop you getting api blocked by doing its own ratelimiting. This would then allow you to safely hook into join/leave.

**Comment by FishyFing** [comment]
With regards to `get_server_count`, that function is there to also get the server count of other bots (if need be), so personally I feel getting the id from the passed bot object wouldn't be useful in this case.

**Comment by tonkku107** [comment]
Hooking into join/leave is not necessary.
Hooking like the js library is now preferred. js lib does every 30 minutes

**Comment by fourjr** [comment]
@FishFing, Bot ID can be an optional argument but it defaults to the current bot

**Comment by fourjr** [comment]
Refer to #3

**Comment by FishyFing** [comment]
TODO:

- [ ] Fix docstrings
- [ ] Implement ratelimits
- [ ] Update README.rst with correct example
  - [ ] Add example for autoposting every 30 mins
  - [ ] PEP8
  - [ ] Class and function descriptions

- [ ] Push to Pypi
