### ISSUE TITLE
403: Forbidden errors

### ISSUE THREAD

**Issue by Pyra1** [DiscordBotList/DBL-Python-Library#5]
I am having an issue.
When I attempt to post server count from the example from https://discordbots.org/api/docs#pylib I get a 403: Forbidden error.
The token is correct. I used the token from https://discordbots.org/api/docs#mybots and I even tested the token in a small discord.js environment and it worked. I am not sure what the problem is.

**Comment by FishyFing** [comment]
@Pyra1 can you please post your OS, dblpy version and the code you were using?

**Comment by RaspberryKitty1** [comment]
I have the same issue and I'm using windows 10 the latest ver of dblpy and the example code from the api website

**Comment by Pyra1** [comment]
I am using Windows 10 Insider Preview Build 17115/rs4_release.180302-1642, the latest dblpy from pip, and the code from the API example.

**Comment by rumblefrog** [comment]
Upon helping another user, it seems like his bot is posting to `https://discordbots.org/api/bots/None/stats`, perhaps more checks should be added to ensure the attribute exist?

**Comment by rumblefrog** [comment]
Update: looks like users were using the old example w/o the ready check, but I believe there should be an internal check as well.

**Comment by DrLarck** [comment]
Hoy !
I got the same error when i'm trying to use the method ``get_upvote_info()``.
Event with a good token, anything works.

**Comment by ajgrinds** [comment]
Did you read the last post? Although very incomplete, it atleast tries to describe the error.

**Comment by shivaco** [comment]
Closing this for now. If error 403 keeps appearing, please let me know.
