### ISSUE TITLE
Module 'dbl' has no 'Client' member

### ISSUE THREAD

**Issue by zomatree** [DiscordBotList/DBL-Python-Library#9]
i have a error on `self.dblpy = dbl.Client(self.bot, self.token) ` its says that 'dbl' has no 'Client' 

![image](https://user-images.githubusercontent.com/39768508/44678609-a8af1a00-aa30-11e8-8a8a-7c5088ad8e87.png)

**Comment by rumblefrog** [comment]
Wow, this is some stale issue w/o reply, but dbl is not clear in that screenshot what it's. Mark invalid as of stale.
